### ISSUE TITLE
sort local variables

### ISSUE THREAD

**Issue by PaulXiCao** [facebook-atom/atom-ide-debugger-native-gdb#8]
the pane shows local variables in the order as they appear in code. an option to sort them _alphabetically_ would be great.

**Comment by ebluestein** [comment]
This is by design and pretty typical, especially of native debuggers.

The order is determined by the underlying debugger engine (in this case gdb) and not by the Nuclide UX.  In environments like C++, the order of local variables and object and struct members is important and significant wrt the memory layout of the variables, as well as the order in which things are initialized, destructed, etc.
